import= ["~/.config/alacritty/color.toml"]
[window]
decorations = "None"
opacity = 0.9
startup_mode = "Maximized"
[font]
normal = {family ="Cousine Nerd Font Mono", style = "Regular"}
bold = {family ="Cousine Nerd Font Mono", style = "Bold"}
italic = {family ="Cousine Nerd Font Mono", style = "Italic"}
bold_italic = {family ="Cousine Nerd Font Mono", style = "Bold Italic"}
size = 13.5
[colors]
