import= ["~/.config/alacritty/color.toml"]
[window]
decorations = "None"
opacity = 0.8
startup_mode = "Maximized"
resize_increments = true 
blur = true
[font]
normal = {family ="Cousine Nerd Font Mono"}
bold = {family ="Cousine Nerd Font Mono"}
italic = {family ="Cousine Nerd Font Mono"}
bold_italic = {family ="Cousine Nerd Font Mono"}
size = 14
[mouse]
hide_when_typing = true
[env]
TERM = "xterm-256color"
