import= ["~/.config/alacritty/color.toml"]
[window]
decorations = "None"
opacity = 0.8
startup_mode = "Fullscreen"
resize_increments = true 
blur = true
[font]
normal = {family ="Hack Nerd Font"}
bold = {family ="Hack Nerd Font"}
italic = {family ="Hack Nerd Font"}
bold_italic = {family ="Hack Nerd Font"}
size = 16
[env]
TERM = "xterm-256color"
