import= ["~/.config/alacritty/color.toml"]
[window]
decorations = "None"
opacity = 0.7
startup_mode = "Maximized"
[font]
normal = {family ="Cousine Nerd Font", style = "Regular"}
bold = {family ="Cousine Nerd Font", style = "Bold"}
italic = {family ="Cousine Nerd Font", style = "Italic"}
bold_italic = {family ="Cousine Nerd Font", style = "Bold Italic"}
size = 10
[colors]
