import= ["~/.config/alacritty/color.toml"]
[window]
decorations = "None"
opacity = 0.7
startup_mode = "Fullscreen"
resize_increments = true 
[font]
normal = {family ="Cousine Nerd Font"}
bold = {family ="Cousine Nerd Font"}
italic = {family ="Cousine Nerd Font"}
bold_italic = {family ="Cousine Nerd Font"}
size = 14
[env]
TERM = "xterm-256color"
