import= ["~/.config/alacritty/color.toml"]
[shell]
program = "tmux"
args = ["new","-At","dacbui308"]
[window]
decorations = "None"
opacity = 0.8
startup_mode = "Maximized"
resize_increments = true 
blur = true
[font]
normal = {family ="MapleMono NF"}
bold = {family ="MapleMono NF"}
italic = {family ="MapleMono NF"}
bold_italic = {family ="MapleMono NF"}
size = 20.1
[mouse]
hide_when_typing = true
[env]
TERM = "xterm-256color"
