# Base16 Ayu Dark - alacritty color config
# Khue Nguyen &lt;Z5483Y@gmail.com&gt;

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x090909'
foreground = '0xe6e1cf'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x0f1419'
cursor = '0xe6e1cf'

# Normal colors
[colors.normal]
black = '0x101010'
red = '0xa00b0b'
green = '0x67c200'
yellow = '0xeed54a'
blue = '0x3c84e5'
magenta = '0x9d0ddf'
cyan = '0x3c7cd8'
white = '0xf0f6ff'

